run:
  timeout: 5m
  tests: true
  skip-dirs-use-default: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gosec
    - misspell
    - unparam
    - nakedret
    - prealloc
    - gocritic
    - gochecknoinits
    - gocyclo
    - gocognit
    - godox
    - funlen
    - whitespace
    - wsl
    - goprintffuncname
    - gomnd
    - goerr113
    - gomodguard
    - godot
    - testpackage
    - nestif
    - exhaustive
    - sqlclosecheck
    - nolintlint
    - paralleltest
  disable:
    - depguard
    - dupl
    - gochecknoglobals
    - gofumpt
    - goconst
    - lll

linters-settings:
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 20
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/axonops/cqlai
  misspell:
    locale: US
  funlen:
    lines: 100
    statements: 60
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Unhandled errors in deferred calls
      - G204  # Subprocess launched with variable

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
    - path: internal/parser/grammar/
      linters:
        - all
    - linters:
        - stylecheck
      text: "ST1003:"
  max-issues-per-linter: 0
  max-same-issues: 0