run:
  timeout: 5m
  tests: true
  skip-dirs:
    - internal/parser/grammar

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gosec
    - misspell
    - gocritic

issues:
  exclude-dirs:
    - internal/parser/grammar