run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gosec
    - misspell
    - gocritic

issues:
  exclude-rules:
    # Exclude generated ANTLR grammar files
    - path: internal/parser/grammar
      linters:
        - all
    # Exclude test files from some linters
    - path: _test\.go
      linters:
        - errcheck
        - gosec