run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  skip-dirs:
    - internal/parser/grammar

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - typecheck
    - gosec
    - misspell
    - unparam
    - gocritic
    - gocyclo
    - funlen
    - whitespace

issues:
  exclude-dirs:
    - internal/parser/grammar
  exclude-files:
    - ".*_gen\\.go$"
    - ".*\\.pb\\.go$"
    - "internal/parser/grammar/.*\\.go$"
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: internal/parser/grammar
      linters:
        - typecheck
        - govet
        - staticcheck