package router

// The CQL statements, from the AxonOps CQL reference:
// https://axonops.com/docs/data-platforms/cassandra/cql/ . The syntax and the
// examples are as the pages give them; each topic links to its page.
var cqlHelpTopics = []HelpTopic{
	{
		Name:    "SELECT",
		Summary: "Retrieves rows and columns from a table.",
		Syntax: []string{
			"SELECT [ JSON | DISTINCT ] select_clause",
			"    FROM [ keyspace_name. ] table_name",
			"    [ WHERE where_clause ]",
			"    [ GROUP BY group_by_clause ]",
			"    [ ORDER BY order_by_clause ]",
			"    [ PER PARTITION LIMIT integer ]",
			"    [ LIMIT integer ]",
			"    [ ALLOW FILTERING ]",
			"",
			"select_clause:",
			"*",
			"| column_name [ AS alias ] [, column_name [ AS alias ] ... ]",
			"| function_name ( [ arguments ] ) [ AS alias ] [, ... ]",
			"| COUNT (*) | COUNT (1)",
			"| CAST ( column_name AS data_type )",
			"| WRITETIME ( column_name )",
			"| TTL ( column_name )",
			"",
			"where_clause:",
			"relation [ AND relation ... ]",
			"",
			"relation:",
			"column_name operator term",
			"| column_name IN ( term [, term ... ] )",
			"| ( column_name [, column_name ... ] )",
			"  IN ( ( term [, term ... ] ) [, ... ] )",
			"| TOKEN ( column_name [, column_name ... ] ) operator term",
			"",
			"operator:",
			"= | < | > | <= | >= | != | CONTAINS | CONTAINS KEY | LIKE",
		},
		Notes: []string{
			"Queries must align with the table's primary key; the partition key must be fully specified for efficient queries.",
			"ORDER BY allows only clustering columns, needs an equality-restricted partition key, and must match or completely reverse the clustering order.",
			"PER PARTITION LIMIT needs 3.6+, GROUP BY aggregates 3.10+, and vector search with ORDER BY ... ANN OF needs 5.0+.",
		},
		Example: []string{
			"SELECT timestamp, temperature, humidity",
			"FROM sensor_readings",
			"WHERE sensor_id = 'temp-001'",
			"  AND date = '2024-01-15'",
			"ORDER BY timestamp DESC",
			"LIMIT 100;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/dml/select/#synopsis",
	},
	{
		Name:    "INSERT",
		Summary: "Adds a row to a table, as an upsert that overwrites any row with the same primary key.",
		Syntax: []string{
			"INSERT INTO [ keyspace_name. ] table_name",
			"    ( column_name [, column_name ... ] )",
			"    VALUES ( term [, term ... ] )",
			"    [ IF NOT EXISTS ]",
			"    [ USING update_parameter [ AND update_parameter ... ] ]",
			"",
			"JSON syntax:",
			"INSERT INTO [ keyspace_name. ] table_name",
			"    JSON 'json_string'",
			"    [ DEFAULT ( NULL | UNSET ) ]",
			"    [ IF NOT EXISTS ]",
			"    [ USING update_parameter [ AND update_parameter ... ] ]",
			"",
			"update_parameter:",
			"TTL seconds",
			"| TIMESTAMP microseconds",
		},
		Notes: []string{
			"All primary key columns must be specified and cannot be null.",
			"IF NOT EXISTS makes the insert a lightweight transaction (Paxos) and cannot be combined with USING TIMESTAMP.",
			"Counter columns cannot be inserted; use UPDATE with an increment.",
		},
		Example: []string{
			"INSERT INTO password_resets (token_id, user_id, created_at)",
			"VALUES (uuid(), 123, toTimestamp(now()))",
			"USING TTL 3600;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/dml/insert/#synopsis",
	},
	{
		Name:    "UPDATE",
		Summary: "Modifies column values in a table, creating the row if it does not exist (upsert).",
		Syntax: []string{
			"UPDATE [ keyspace_name. ] table_name",
			"    [ USING update_parameter [ AND update_parameter ... ] ]",
			"    SET assignment [, assignment ... ]",
			"    WHERE where_clause",
			"    [ IF condition [ AND condition ... ] | IF EXISTS ]",
			"",
			"update_parameter:",
			"TTL seconds",
			"| TIMESTAMP microseconds",
			"",
			"assignment:",
			"column_name = term",
			"| column_name = column_name + term",
			"| column_name = term + column_name",
			"| column_name = column_name - term",
			"| column_name [ index ] = term",
			"| column_name [ key ] = term",
			"| column_name.field_name = term",
			"",
			"condition:",
			"column_name operator term",
			"| column_name [ index ] operator term",
			"| column_name [ key ] operator term",
			"| column_name IN ( term [, term ... ] )",
		},
		Notes: []string{
			"All partition key columns are required in WHERE, and primary key columns cannot be SET.",
			"Counter columns only support +/- operations and do not support IF conditions.",
			"IF cannot be used with USING TIMESTAMP.",
		},
		Example: []string{
			"UPDATE sessions USING TTL 3600",
			"SET token = 'refreshed_token_xyz',",
			"    last_activity = toTimestamp(now())",
			"WHERE session_id = ?;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/dml/update/#synopsis",
	},
	{
		Name:    "DELETE",
		Summary: "Removes rows or column values from a table by writing tombstones.",
		Syntax: []string{
			"DELETE [ column_name [ , column_name ... ] ]",
			"    FROM [ keyspace_name. ] table_name",
			"    [ USING TIMESTAMP microseconds ]",
			"    WHERE where_clause",
			"    [ IF condition [ AND condition ... ] | IF EXISTS ]",
			"",
			"column_name (optional):",
			"column_name",
			"| column_name [ list_index ]",
			"| column_name [ map_key ]",
		},
		Notes: []string{
			"The partition key is required, ALLOW FILTERING cannot be used, and range deletes work only on clustering columns.",
			"Deleted data is marked with tombstones that persist until gc_grace_seconds passes and compaction removes them.",
			"IF cannot be used with USING TIMESTAMP.",
		},
		Example: []string{
			"DELETE FROM active_events",
			"WHERE tenant_id = 'acme'",
			"  AND event_time < '2024-01-01';",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/dml/delete/#synopsis",
	},
	{
		Name: "BATCH",
		Aliases: []string{
			"BEGIN BATCH",
			"BEGIN UNLOGGED BATCH",
			"BEGIN COUNTER BATCH",
			"APPLY BATCH",
		},
		Summary: "Groups multiple INSERT, UPDATE and DELETE statements into a single logical operation.",
		Syntax: []string{
			"BEGIN [ UNLOGGED | COUNTER ] BATCH",
			"    [ USING TIMESTAMP microseconds ]",
			"    dml_statement ;",
			"    [ dml_statement ; ... ]",
			"APPLY BATCH",
			"",
			"dml_statement:",
			"INSERT ... | UPDATE ... | DELETE ...",
		},
		Notes: []string{
			"Same-partition batches are atomic; multi-partition logged batches give durability via the batch log but not atomicity.",
			"Batches are not a performance optimization and are slower than individual writes for unrelated data.",
			"Counter batches must use COUNTER; conditional batches must keep all IF conditions on one partition and cannot use USING TIMESTAMP.",
		},
		Example: []string{
			"BEGIN BATCH",
			"    INSERT INTO users (user_id, email, username, created_at)",
			"    VALUES (?, 'alice@example.com', 'alice', toTimestamp(now()));",
			"",
			"    INSERT INTO users_by_email (email, user_id, username)",
			"    VALUES ('alice@example.com', ?, 'alice');",
			"APPLY BATCH;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/dml/batch/#synopsis",
	},
	{
		Name:    "CREATE KEYSPACE",
		Summary: "Creates a new keyspace with the given replication configuration.",
		Syntax: []string{
			"CREATE KEYSPACE [ IF NOT EXISTS ] keyspace_name",
			"    WITH REPLICATION = { replication_map }",
			"    [ AND DURABLE_WRITES = { true | false } ]",
			"",
			"replication_map:",
			"{ 'class': 'strategy_name' [, strategy_options ] }",
		},
		Notes: []string{
			"REPLICATION is required; strategy_name is SimpleStrategy (development) or NetworkTopologyStrategy (production).",
			"Never use SimpleStrategy in production multi-datacenter deployments.",
			"DURABLE_WRITES = false bypasses the commit log and risks data loss on node failure.",
		},
		Example: []string{
			"CREATE KEYSPACE prod_keyspace",
			"WITH REPLICATION = {",
			"    'class': 'NetworkTopologyStrategy',",
			"    'datacenter1': 3",
			"};",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/ddl/keyspace/#create-keyspace",
	},
	{
		Name:    "ALTER KEYSPACE",
		Summary: "Changes the replication strategy or options of an existing keyspace.",
		Syntax: []string{
			"ALTER KEYSPACE keyspace_name",
			"    WITH REPLICATION = { replication_map }",
			"    [ AND DURABLE_WRITES = { true | false } ]",
		},
		Notes: []string{
			"The new replication map completely replaces the existing one; include every datacenter you want to keep.",
			"Existing data is not redistributed; run nodetool repair (or nodetool rebuild for a new datacenter) afterwards.",
			"The keyspace name cannot be changed and system keyspaces cannot be altered.",
		},
		Example: []string{
			"ALTER KEYSPACE my_keyspace",
			"WITH REPLICATION = {",
			"    'class': 'NetworkTopologyStrategy',",
			"    'datacenter1': 5",
			"};",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/ddl/keyspace/#alter-keyspace",
	},
	{
		Name:    "DROP KEYSPACE",
		Summary: "Permanently removes a keyspace and every object and row in it.",
		Syntax: []string{
			"DROP KEYSPACE [ IF EXISTS ] keyspace_name",
		},
		Notes: []string{
			"Dropping a keyspace cannot be undone.",
			"With auto_snapshot: true (the default) Cassandra takes a snapshot before deleting the data.",
			"System keyspaces cannot be dropped.",
		},
		Example: []string{
			"DROP KEYSPACE IF EXISTS temp_keyspace;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/ddl/keyspace/#drop-keyspace",
	},
	{
		Name:    "USE",
		Summary: "Sets the default keyspace for later statements in the current session.",
		Syntax: []string{
			"USE keyspace_name",
		},
		Notes: []string{
			"It is a session-level setting that does not affect other connections or persist across sessions.",
			"The keyspace must exist, and there is no IF EXISTS clause.",
			"Application code should prefer fully qualified table names over USE.",
		},
		Example: []string{
			"USE my_keyspace;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/ddl/keyspace/#use",
	},
	{
		Name: "CREATE TABLE",
		Aliases: []string{
			"CREATE COLUMNFAMILY",
		},
		Summary: "Defines a new table with its columns, primary key and storage options.",
		Syntax: []string{
			"CREATE TABLE [ IF NOT EXISTS ] [ keyspace_name. ] table_name",
			"    ( column_definition [, column_definition ... ] ,",
			"      PRIMARY KEY ( primary_key ) )",
			"    [ WITH table_options ]",
			"",
			"column_definition:",
			"column_name data_type [ STATIC ] [ PRIMARY KEY ]",
			"",
			"primary_key:",
			"partition_key",
			"| ( partition_key [, clustering_column ... ] )",
			"",
			"partition_key:",
			"column_name",
			"| ( column_name [, column_name ... ] )",
			"",
			"table_options:",
			"option = value [ AND option = value ... ]",
			"| CLUSTERING ORDER BY ( column_name [ ASC | DESC ] [, ... ] )",
			"| COMPACT STORAGE",
			"| ID = table_id",
		},
		Notes: []string{
			"The primary key cannot be changed after the table is created.",
			"Collections cannot be primary key components unless FROZEN, and COUNTER columns need a dedicated table.",
			"COMPACT STORAGE is deprecated and should not be used for new tables.",
		},
		Example: []string{
			"CREATE TABLE users (",
			"    user_id UUID PRIMARY KEY,",
			"    username TEXT,",
			"    email TEXT,",
			"    created_at TIMESTAMP",
			");",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/ddl/table/#create-table",
	},
	{
		Name: "ALTER TABLE",
		Aliases: []string{
			"ALTER COLUMNFAMILY",
		},
		Summary: "Adds, drops or renames columns, or changes table options.",
		Syntax: []string{
			"ALTER TABLE [ keyspace_name. ] table_name alter_instruction",
			"",
			"alter_instruction:",
			"ADD column_name data_type [ STATIC ] [, column_name data_type ... ]",
			"| DROP column_name [, column_name ... ]",
			"| RENAME column_name TO new_name [ AND column_name TO new_name ... ]",
			"| WITH table_options",
		},
		Notes: []string{
			"Adding a column is metadata-only; dropped column data is removed later by compaction.",
			"RENAME works only on clustering columns.",
			"Primary key columns cannot be added or dropped, and column data types cannot be changed.",
		},
		Example: []string{
			"ALTER TABLE users ADD phone TEXT, address TEXT, age INT;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/ddl/table/#alter-table",
	},
	{
		Name: "DROP TABLE",
		Aliases: []string{
			"DROP COLUMNFAMILY",
		},
		Summary: "Permanently removes a table with all its data, indexes and materialized views.",
		Syntax: []string{
			"DROP TABLE [ IF EXISTS ] [ keyspace_name. ] table_name",
		},
		Notes: []string{
			"Dropping a table cannot be undone.",
			"With auto_snapshot: true (the default) Cassandra takes a snapshot before deleting the data.",
			"Requires DROP permission on the table; system tables cannot be dropped.",
		},
		Example: []string{
			"DROP TABLE IF EXISTS temp_data;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/ddl/table/#drop-table",
	},
	{
		Name:    "TRUNCATE",
		Summary: "Removes all rows from a table while keeping its schema, indexes and materialized views.",
		Syntax: []string{
			"TRUNCATE [ TABLE ] [ keyspace_name. ] table_name",
		},
		Notes: []string{
			"Requires every node holding replicas to be available; it fails if any node is down.",
			"Takes an automatic snapshot by default (auto_snapshot in cassandra.yaml).",
			"Does not generate tombstones, unlike DELETE.",
		},
		Example: []string{
			"TRUNCATE TABLE my_keyspace.events;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/ddl/table/#truncate",
	},
	{
		Name: "CREATE INDEX",
		Aliases: []string{
			"CREATE CUSTOM INDEX",
		},
		Summary: "Creates a secondary index (legacy, SAI or SASI) on a table column.",
		Syntax: []string{
			"CREATE [ CUSTOM ] INDEX [ IF NOT EXISTS ] [ index_name ]",
			"    ON [ keyspace_name. ] table_name ( index_target )",
			"    [ USING 'index_class' ]",
			"    [ WITH OPTIONS = { option_map } ]",
			"",
			"index_target:",
			"column_name",
			"| KEYS ( map_column )",
			"| VALUES ( map_column )",
			"| ENTRIES ( map_column )",
			"| FULL ( frozen_collection_column )",
		},
		Notes: []string{
			"The index is built asynchronously; the statement returns before indexing completes.",
			"SAI (USING 'StorageAttachedIndex', Cassandra 5.0+) supports range queries and LIKE; SASI is experimental.",
			"Partition key columns and COUNTER columns cannot be indexed.",
		},
		Example: []string{
			"CREATE CUSTOM INDEX ON users (username)",
			"    USING 'StorageAttachedIndex'",
			"    WITH OPTIONS = {'case_sensitive': 'false'};",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/ddl/create-index/#create-index",
	},
	{
		Name:    "DROP INDEX",
		Summary: "Removes a secondary index.",
		Syntax: []string{
			"DROP INDEX [ IF EXISTS ] [ keyspace_name. ] index_name",
		},
		Notes: []string{
			"Queries that use the index fail after it is dropped.",
			"The index name must be keyspace-qualified if no keyspace is set with USE.",
			"Requires DROP permission on the table.",
		},
		Example: []string{
			"DROP INDEX my_keyspace.users_email_idx;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/ddl/create-index/#drop-index",
	},
	{
		Name:    "CREATE MATERIALIZED VIEW",
		Summary: "Creates a server-maintained view of a base table with a different primary key.",
		Syntax: []string{
			"CREATE MATERIALIZED VIEW [ IF NOT EXISTS ] [ keyspace_name. ] view_name",
			"    AS SELECT select_clause",
			"    FROM [ keyspace_name. ] base_table",
			"    WHERE where_clause",
			"    PRIMARY KEY ( primary_key )",
			"    [ WITH table_options ]",
		},
		Notes: []string{
			"Materialized views are experimental and can become inconsistent with the base table; evaluate carefully before production use.",
			"WHERE must include IS NOT NULL for every view primary key column, and the view key must contain all base key columns plus at most one other column.",
			"The view is built asynchronously; check progress with nodetool viewbuildstatus.",
		},
		Example: []string{
			"CREATE MATERIALIZED VIEW users_by_email AS",
			"    SELECT *",
			"    FROM users",
			"    WHERE email IS NOT NULL",
			"      AND user_id IS NOT NULL",
			"    PRIMARY KEY (email, user_id);",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/ddl/materialized-view/#create-materialized-view",
	},
	{
		Name:    "ALTER MATERIALIZED VIEW",
		Summary: "Changes the storage options of a materialized view.",
		Syntax: []string{
			"ALTER MATERIALIZED VIEW [ keyspace_name. ] view_name",
			"    WITH table_options",
		},
		Notes: []string{
			"Only options such as compaction, compression, gc_grace_seconds, caching, bloom_filter_fp_chance and speculative_retry can change.",
			"The view name, columns, primary key, base table and WHERE filters cannot be modified.",
		},
		Example: []string{
			"ALTER MATERIALIZED VIEW events_recent",
			"WITH gc_grace_seconds = 172800;  -- 2 days",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/ddl/materialized-view/#alter-materialized-view",
	},
	{
		Name:    "DROP MATERIALIZED VIEW",
		Summary: "Removes a materialized view and all its data, leaving the base table unchanged.",
		Syntax: []string{
			"DROP MATERIALIZED VIEW [ IF EXISTS ] [ keyspace_name. ] view_name",
		},
		Notes: []string{
			"Requires DROP permission on the view.",
			"Dropping the base table drops all its views.",
			"It cannot be undone; take a snapshot first if needed.",
		},
		Example: []string{
			"DROP MATERIALIZED VIEW IF EXISTS temp_view;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/ddl/materialized-view/#drop-materialized-view",
	},
	{
		Name:    "CREATE TRIGGER",
		Summary: "Attaches a Java trigger class to a table so it runs on each mutation.",
		Syntax: []string{
			"CREATE TRIGGER [ IF NOT EXISTS ] trigger_name",
			"    ON [keyspace_name.]table_name",
			"    USING 'fully.qualified.ClassName'",
		},
		Notes: []string{
			"Requires superuser privileges.",
			"The trigger JAR must be deployed to every node and the table must exist.",
			"Triggers run on the coordinator before the mutation is applied; an exception rejects the whole mutation.",
		},
		Example: []string{
			"CREATE TRIGGER audit_trigger",
			"    ON users",
			"    USING 'com.example.triggers.AuditTrigger';",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/ddl/trigger/#create-trigger",
	},
	{
		Name:    "DROP TRIGGER",
		Summary: "Removes a trigger from a table.",
		Syntax: []string{
			"DROP TRIGGER [ IF EXISTS ] trigger_name",
			"    ON [keyspace_name.]table_name",
		},
		Example: []string{
			"DROP TRIGGER IF EXISTS old_trigger ON orders;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/ddl/trigger/#drop-trigger",
	},
	{
		Name:    "CREATE TYPE",
		Summary: "Defines a user-defined type (UDT) with named fields, scoped to a keyspace.",
		Syntax: []string{
			"CREATE TYPE [ IF NOT EXISTS ] [ keyspace_name. ] type_name",
			"    ( field_name data_type [, field_name data_type ... ] )",
		},
		Notes: []string{
			"UDTs must be FROZEN when used in collections, primary key columns or index columns.",
			"UDTs cannot reference themselves and cannot be used directly from another keyspace.",
			"Types must be created before the tables that reference them.",
		},
		Example: []string{
			"CREATE TYPE address (",
			"    street TEXT,",
			"    city TEXT,",
			"    state TEXT,",
			"    postal_code TEXT,",
			"    country TEXT",
			");",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/ddl/type/#create-type",
	},
	{
		Name:    "ALTER TYPE",
		Summary: "Adds new fields to, or renames fields of, a user-defined type.",
		Syntax: []string{
			"ALTER TYPE [ keyspace_name. ] type_name alter_instruction",
			"",
			"alter_instruction:",
			"ADD field_name data_type",
			"| RENAME field_name TO new_name [ AND field_name TO new_name ... ]",
		},
		Notes: []string{
			"Fields cannot be removed, reordered, or have their types changed.",
			"New fields are added at the end and read as null in existing data.",
			"Changes apply to every table that uses the type.",
		},
		Example: []string{
			"ALTER TYPE address ADD county TEXT;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/ddl/type/#alter-type",
	},
	{
		Name:    "DROP TYPE",
		Summary: "Removes a user-defined type definition.",
		Syntax: []string{
			"DROP TYPE [ IF EXISTS ] [ keyspace_name. ] type_name",
		},
		Notes: []string{
			"The type must not be in use by any table column, materialized view or other UDT; drop dependent objects first.",
			"System types cannot be dropped.",
		},
		Example: []string{
			"DROP TYPE IF EXISTS temp_type;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/ddl/type/#drop-type",
	},
	{
		Name: "CREATE FUNCTION",
		Aliases: []string{
			"CREATE OR REPLACE FUNCTION",
		},
		Summary: "Creates a user-defined scalar function (UDF) written in Java or JavaScript.",
		Syntax: []string{
			"CREATE [ OR REPLACE ] FUNCTION [ IF NOT EXISTS ]",
			"    [ keyspace_name. ] function_name",
			"    ( [ arg_name arg_type [, arg_name arg_type ... ] ] )",
			"    { CALLED ON NULL INPUT | RETURNS NULL ON NULL INPUT }",
			"    RETURNS return_type",
			"    LANGUAGE { java | javascript }",
			"    AS 'function_body'",
		},
		Notes: []string{
			"UDFs must be enabled in cassandra.yaml (enable_user_defined_functions; enable_scripted_user_defined_functions for JavaScript).",
			"IF NOT EXISTS cannot be combined with OR REPLACE.",
			"Functions are keyspace-scoped and can be overloaded by argument types.",
		},
		Example: []string{
			"CREATE FUNCTION double_value(input INT)",
			"    RETURNS NULL ON NULL INPUT",
			"    RETURNS INT",
			"    LANGUAGE java",
			"    AS 'return input * 2;';",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/ddl/function/#create-function",
	},
	{
		Name:    "DROP FUNCTION",
		Summary: "Removes a user-defined function.",
		Syntax: []string{
			"DROP FUNCTION [ IF EXISTS ] [ keyspace_name. ] function_name",
			"    [ ( [ arg_type [, arg_type ... ] ] ) ]",
		},
		Notes: []string{
			"If the function is overloaded, give the argument types to pick the overload.",
			"Functions used by aggregates cannot be dropped; drop the aggregate first.",
			"Requires DROP permission on the function.",
		},
		Example: []string{
			"DROP FUNCTION concat(TEXT, TEXT);",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/ddl/function/#drop-function",
	},
	{
		Name: "CREATE AGGREGATE",
		Aliases: []string{
			"CREATE OR REPLACE AGGREGATE",
		},
		Summary: "Creates a user-defined aggregate (UDA) built from a state function and an optional final function.",
		Syntax: []string{
			"CREATE [ OR REPLACE ] AGGREGATE [ IF NOT EXISTS ]",
			"    [ keyspace_name. ] aggregate_name",
			"    ( [ arg_type [, arg_type ... ] ] )",
			"    SFUNC state_function",
			"    STYPE state_type",
			"    [ FINALFUNC final_function ]",
			"    [ INITCOND initial_condition ]",
		},
		Notes: []string{
			"UDFs must be enabled in cassandra.yaml, and SFUNC must exist before the aggregate is created.",
			"SFUNC must take STYPE as its first parameter and return STYPE; FINALFUNC must accept STYPE.",
			"Aggregates execute on the coordinator only.",
		},
		Example: []string{
			"CREATE AGGREGATE my_sum(INT)",
			"    SFUNC sum_state",
			"    STYPE BIGINT",
			"    INITCOND 0;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/ddl/aggregate/#create-aggregate",
	},
	{
		Name:    "DROP AGGREGATE",
		Summary: "Removes a user-defined aggregate.",
		Syntax: []string{
			"DROP AGGREGATE [ IF EXISTS ] [ keyspace_name. ] aggregate_name",
			"    [ ( [ arg_type [, arg_type ... ] ] ) ]",
		},
		Notes: []string{
			"Give the argument types if the aggregate has overloads.",
			"Dropping an aggregate does not drop its underlying functions.",
			"Requires DROP permission.",
		},
		Example: []string{
			"DROP AGGREGATE IF EXISTS temp_aggregate;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/ddl/aggregate/#drop-aggregate",
	},
	{
		Name:    "CREATE ROLE",
		Summary: "Creates a role for authentication, authorization, or both.",
		Syntax: []string{
			"CREATE ROLE [ IF NOT EXISTS ] role_name",
			"    [ WITH option [ AND option ... ] ]",
		},
		Notes: []string{
			"Options are PASSWORD, HASHED PASSWORD, LOGIN, SUPERUSER and OPTIONS; LOGIN and SUPERUSER default to false.",
			"Requires CREATE permission on ALL ROLES, or superuser.",
			"PASSWORD is required when LOGIN = true.",
		},
		Example: []string{
			"CREATE ROLE app_service",
			"    WITH PASSWORD = 'secret123'",
			"    AND LOGIN = true;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/security/rbac/#create-role",
	},
	{
		Name:    "ALTER ROLE",
		Summary: "Changes the properties of a role.",
		Syntax: []string{
			"ALTER ROLE [ IF EXISTS ] role_name",
			"    [ WITH option [ AND option ... ] ]",
		},
		Notes: []string{
			"Accepts the same options as CREATE ROLE; with IF EXISTS it is a no-op when the role does not exist.",
			"Requires ALTER permission on the role, or superuser; non-superusers can only change their own password.",
			"The last superuser cannot be demoted.",
		},
		Example: []string{
			"ALTER ROLE app_service WITH PASSWORD = 'new_password';",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/security/rbac/#alter-role",
	},
	{
		Name:    "DROP ROLE",
		Summary: "Removes a role.",
		Syntax: []string{
			"DROP ROLE [ IF EXISTS ] role_name",
		},
		Notes: []string{
			"Requires DROP permission on the role, or superuser.",
			"The last superuser cannot be dropped.",
			"Active sessions continue but re-authentication fails.",
		},
		Example: []string{
			"DROP ROLE IF EXISTS temp_user;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/security/rbac/#drop-role",
	},
	{
		Name:    "GRANT",
		Summary: "Grants permissions on a resource to a role, or grants one role to another to create role membership.",
		Syntax: []string{
			"GRANT ( ALL [ PERMISSIONS ] | permission ) ON resource TO role_name",
			"",
			"GRANT role_name TO role_name",
		},
		Notes: []string{
			"permission is one of CREATE, ALTER, DROP, SELECT, MODIFY, AUTHORIZE, DESCRIBE, UNMASK, SELECT_MASKED, EXECUTE.",
			"Granting permissions needs AUTHORIZE on the resource; granting a role needs AUTHORIZE on both roles (or superuser).",
			"Circular role grants are not allowed.",
		},
		Example: []string{
			"GRANT SELECT ON KEYSPACE production TO analyst;",
			"GRANT prod_read TO app_service;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/security/rbac/#grant-permission",
	},
	{
		Name:    "REVOKE",
		Summary: "Removes permissions from a role, or removes a role membership.",
		Syntax: []string{
			"REVOKE ( ALL [ PERMISSIONS ] | permission ) ON resource FROM role_name",
			"",
			"REVOKE role_name FROM role_name",
		},
		Notes: []string{
			"permission and resource accept the same forms as in GRANT.",
			"Requires AUTHORIZE permission on the resource, or superuser.",
			"Revoking a permission that does not exist succeeds silently.",
		},
		Example: []string{
			"REVOKE MODIFY ON KEYSPACE production FROM app_service;",
			"REVOKE prod_write FROM restricted_user;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/security/rbac/#revoke-permission",
	},
	{
		Name:    "LIST ROLES",
		Summary: "Displays roles and their properties.",
		Syntax: []string{
			"LIST ROLES [ OF role_name ] [ NORECURSIVE ]",
		},
		Notes: []string{
			"OF role_name shows the roles granted to that role, including inherited ones.",
			"NORECURSIVE shows only direct grants.",
		},
		Example: []string{
			"LIST ROLES OF app_user NORECURSIVE;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/security/rbac/#list-roles",
	},
	{
		Name: "LIST PERMISSIONS",
		Aliases: []string{
			"LIST ALL PERMISSIONS",
			"LIST ALL",
		},
		Summary: "Displays granted permissions, optionally filtered by permission, resource and role.",
		Syntax: []string{
			"LIST ( ALL [ PERMISSIONS ] | permission )",
			"    [ ON resource ]",
			"    [ OF role_name [ NORECURSIVE ] ]",
		},
		Notes: []string{
			"Permissions inherited through granted roles are included unless NORECURSIVE is given.",
		},
		Example: []string{
			"LIST ALL PERMISSIONS OF app_service;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/security/rbac/#list-permissions",
	},
	{
		Name:    "ADD IDENTITY",
		Summary: "Associates a certificate identity with a role.",
		Syntax: []string{
			"ADD IDENTITY [ IF NOT EXISTS ] 'identity_string' TO ROLE role_name",
		},
		Notes: []string{
			"Requires MutualTlsAuthenticator and Cassandra 5.0+.",
			"With IF NOT EXISTS it is a no-op when the identity is already associated.",
		},
		Example: []string{
			"ADD IDENTITY 'CN=app-client,O=MyOrg' TO ROLE app_client;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/security/rbac/#add-identity",
	},
	{
		Name:    "DROP IDENTITY",
		Summary: "Removes a certificate identity mapping.",
		Syntax: []string{
			"DROP IDENTITY [ IF EXISTS ] 'identity_string'",
		},
		Notes: []string{
			"Available in Cassandra 5.0+.",
			"With IF EXISTS it is a no-op when the identity does not exist.",
		},
		Example: []string{
			"DROP IDENTITY 'spiffe://cluster.local/ns/default/sa/app-service';",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/security/rbac/#drop-identity",
	},
	{
		Name:    "CREATE USER",
		Summary: "Creates a login role using the legacy pre-2.2 user syntax.",
		Syntax: []string{
			"CREATE USER [ IF NOT EXISTS ] user_name",
			"    [ WITH PASSWORD 'password' ]",
			"    [ SUPERUSER | NOSUPERUSER ]",
		},
		Notes: []string{
			"Internally executes CREATE ROLE ... WITH LOGIN = true.",
			"SUPERUSER and NOSUPERUSER map to SUPERUSER = true|false; the default is NOSUPERUSER.",
			"Kept for backward compatibility; prefer CREATE ROLE for new deployments.",
		},
		Example: []string{
			"CREATE USER IF NOT EXISTS app_user WITH PASSWORD 'secret' NOSUPERUSER;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/security/rbac/#create-user",
	},
	{
		Name:    "ALTER USER",
		Summary: "Changes a user's password or superuser status using the legacy user syntax.",
		Syntax: []string{
			"ALTER USER [ IF EXISTS ] user_name",
			"    [ WITH PASSWORD 'password' ]",
			"    [ SUPERUSER | NOSUPERUSER ]",
		},
		Notes: []string{
			"Kept for backward compatibility; prefer ALTER ROLE for new deployments.",
		},
		Example: []string{
			"ALTER USER app_user WITH PASSWORD 'rotated_secret';",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/security/rbac/#alter-user",
	},
	{
		Name:    "DROP USER",
		Summary: "Removes a user using the legacy user syntax.",
		Syntax: []string{
			"DROP USER [ IF EXISTS ] user_name",
		},
		Notes: []string{
			"Kept for backward compatibility; prefer DROP ROLE for new deployments.",
		},
		Example: []string{
			"DROP USER IF EXISTS legacy_user;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/security/rbac/#drop-user",
	},
	{
		Name:    "LIST USERS",
		Summary: "Lists users using the legacy user syntax.",
		Syntax: []string{
			"LIST USERS",
		},
		Notes: []string{
			"Returns the subset of roles where LOGIN = true.",
		},
		Example: []string{
			"LIST USERS;",
		},
		URL: "https://axonops.com/docs/data-platforms/cassandra/cql/security/rbac/#list-users",
	},
}
