package router

// The shell's own commands: what cqlai takes besides CQL, as its parser reads
// them.
var shellHelpTopics = []HelpTopic{
	{
		Name:    "CONSISTENCY",
		Summary: "Shows or sets the consistency level of the queries this shell runs.",
		Syntax: []string{
			"CONSISTENCY",
			"CONSISTENCY level",
			"",
			"level: ANY | ONE | TWO | THREE | QUORUM | ALL | LOCAL_ONE | LOCAL_QUORUM",
			"       | EACH_QUORUM | SERIAL | LOCAL_SERIAL",
		},
		Notes: []string{
			"LOCAL QUORUM, LOCAL ONE, LOCAL SERIAL and EACH QUORUM work with a space too.",
			"It starts at LOCAL_ONE unless the settings or the command line say otherwise.",
			"The status line's CL field sets it with the mouse.",
		},
		Example: []string{"CONSISTENCY LOCAL_QUORUM"},
	},
	{
		Name:    "TRACING",
		Summary: "Shows whether queries are traced, or turns tracing on or off.",
		Syntax:  []string{"TRACING", "TRACING ON | OFF"},
		Notes:   []string{"With it on, each query's trace is in the TRACE view (F5)."},
		Example: []string{"TRACING ON"},
	},
	{
		Name:    "PAGING",
		Summary: "Shows or sets how many rows are fetched at a time.",
		Syntax:  []string{"PAGING", "PAGING rows", "PAGING OFF"},
		Notes:   []string{"OFF leaves the page size to the server. It is 100 unless the settings say otherwise."},
		Example: []string{"PAGING 500"},
	},
	{
		Name:    "AUTOFETCH",
		Summary: "Shows whether every page is fetched at once, or turns it on or off.",
		Syntax:  []string{"AUTOFETCH", "AUTOFETCH ON | OFF"},
		Notes:   []string{"Off, a result is read a page at a time as you scroll to its end."},
		Example: []string{"AUTOFETCH ON"},
	},
	{
		Name:    "EXPAND",
		Summary: "Shows each row as a list of column and value, or goes back to the table.",
		Syntax:  []string{"EXPAND", "EXPAND ON | OFF"},
		Notes:   []string{"EXPAND ON is OUTPUT EXPAND; EXPAND OFF is OUTPUT TABLE."},
		Example: []string{"EXPAND ON"},
	},
	{
		Name:    "OUTPUT",
		Summary: "Shows or sets how results are drawn, and redraws the one on screen.",
		Syntax:  []string{"OUTPUT", "OUTPUT TABLE | ASCII | EXPAND | JSON"},
		Example: []string{"OUTPUT JSON"},
	},
	{
		Name:    "DESCRIBE",
		Aliases: []string{"DESC"},
		Summary: "Shows the definition of the schema, or lists what is in it.",
		Syntax: []string{
			"DESCRIBE KEYSPACES | TABLES [pattern] | TYPES | FUNCTIONS | AGGREGATES",
			"DESCRIBE MATERIALIZED VIEWS",
			"DESCRIBE KEYSPACE keyspace",
			"DESCRIBE TABLE [keyspace.]table",
			"DESCRIBE TYPE [keyspace.]type",
			"DESCRIBE FUNCTION [keyspace.]function",
			"DESCRIBE AGGREGATE [keyspace.]aggregate",
			"DESCRIBE INDEX [keyspace.]index",
			"DESCRIBE MATERIALIZED VIEW [keyspace.]view",
			"DESCRIBE CLUSTER | SCHEMA",
			"DESCRIBE name",
		},
		Notes: []string{
			"DESC is the same. A name on its own is a table, then a keyspace. TABLES",
			"takes a pattern with * at the start, the end or the middle. The SCHEMA",
			"view (F3) shows the same definitions as a tree.",
		},
		Example: []string{"DESCRIBE TABLE shop.orders"},
	},
	{
		Name:    "SHOW",
		Summary: "Shows the Cassandra version, the node connected to, or this session's settings.",
		Syntax:  []string{"SHOW VERSION | HOST | SESSION"},
		Example: []string{"SHOW SESSION"},
	},
	{
		Name:    "SOURCE",
		Summary: "Runs the CQL statements in a file, one after another.",
		Syntax:  []string{"SOURCE 'file'"},
		Notes: []string{
			"The quotes can be left out. ~ is the home directory. Each statement ends",
			"with a semicolon, as at the prompt: one in a string or a comment does not",
			"count, and a BEGIN BATCH runs whole. A file cannot source itself.",
		},
		Example: []string{"SOURCE '~/schema/shop.cql'"},
	},
	{
		Name:    "COPY",
		Aliases: []string{"COPY TO", "COPY FROM"},
		Summary: "Exports a table to a CSV or Parquet file, or imports one into a table.",
		Syntax: []string{
			"COPY [keyspace.]table [(column, ...)] TO 'file' | STDOUT [WITH option = value [AND ...]];",
			"COPY [keyspace.]table [(column, ...)] FROM 'file' | STDIN [WITH option = value [AND ...]];",
			"",
			"CSV:     HEADER = true | false, DELIMITER = ',', NULLVAL = 'null', QUOTE = '\"'",
			"TO only:  PAGESIZE = 1000",
			"FROM only: SKIPROWS = 0, MAXROWS = -1, MAXPARSEERRORS = -1,",
			"          MAXINSERTERRORS = 1000, MAXBATCHSIZE = 20, MAXREQUESTS = 6",
			"Parquet: FORMAT = 'parquet', COMPRESSION = snappy | gzip | lz4 | zstd | none,",
			"         PARTITION = 'column, ...' (TO), MAX_FILE_SIZE = '100MB' (TO),",
			"         CHUNKSIZE, LIMIT (TO), PARTITION_FILTER = 'key=value, ...' (FROM)",
		},
		Notes: []string{
			"A file ending .parquet is Parquet without FORMAT; anything else is CSV. With",
			"PARTITION the target is a directory of Hive-style partitions, and FROM",
			"reads such a directory. Unlike the shell's other commands, COPY needs its ;.",
			"In CSV each value is written as Cassandra writes it, and a collection, tuple",
			"or UDT as JSON. FROM has Cassandra read each field as its column's type, and",
			"leaves columns the file does not have as they are.",
		},
		Example: []string{
			"COPY shop.orders TO 'orders.csv' WITH HEADER = true;",
			"COPY shop.orders FROM 'orders.parquet';",
		},
	},
	{
		Name:    "SAVE",
		Summary: "Saves the result on screen to a CSV, JSON or Parquet file.",
		Syntax: []string{
			"SAVE",
			"SAVE TO 'file' [AS CSV | JSON | PARQUET] [WITH option = value [, ...]]",
			"",
			"CSV:     header = true | false (true)",
			"JSON:    pretty = true | false (false)",
			"Parquet: compression = snappy | gzip | lz4 | zstd | none (snappy)",
		},
		Notes: []string{
			"SAVE on its own opens the save window. Without AS the file's ending says",
			"which, and CSV is the default. ~ is the home directory.",
		},
		Example: []string{"SAVE TO '~/orders.json' AS JSON WITH pretty = true"},
	},
	{
		Name:    "AUTOSAVE",
		Aliases: []string{"CAPTURE"},
		Summary: "Saves every result from now on to a file of its own, in a directory.",
		Syntax: []string{
			"AUTOSAVE",
			"AUTOSAVE [CSV | JSON | PARQUET] 'directory' [WITH option = value [AND ...]]",
			"AUTOSAVE OFF",
			"",
			"Parquet: PARTITION = 'column, ...', COMPRESSION = snappy | gzip | lz4 | zstd | none,",
			"         MAX_FILE_SIZE = '100MB'",
		},
		Notes: []string{
			"AUTOSAVE on its own opens its window. Without a format each result is a",
			".txt file as it was drawn. CAPTURE is the same command, cqlsh's name for",
			"it. Write AND in capitals between options.",
		},
		Example: []string{"AUTOSAVE PARQUET '~/captures' WITH COMPRESSION = zstd"},
	},
	{
		Name:    "HELP",
		Summary: "Opens this window: everything there is, or how one command is written.",
		Syntax:  []string{"HELP", "HELP command"},
		Notes:   []string{"F1 or Alt+H opens it too. Drag over its text to copy it. Ctrl+click a link to open it."},
		Example: []string{"HELP CREATE TABLE"},
	},
	{
		Name:    "CLEAR",
		Aliases: []string{"CLS"},
		Summary: "Clears the console.",
		Syntax:  []string{"CLEAR", "CLS"},
	},
	{
		Name:    "EXIT",
		Aliases: []string{"QUIT"},
		Summary: "Leaves cqlai, asking first.",
		Syntax:  []string{"EXIT", "QUIT"},
		Notes:   []string{"Ctrl+D and Ctrl+Q do the same, and FILE > QUIT."},
	},
	{
		Name:    "MOUSE",
		Summary: "Shows whether cqlai has the mouse, or gives it back to the terminal.",
		Syntax:  []string{"MOUSE", "MOUSE ON | OFF"},
		Notes: []string{
			"On, the tabs and the status line are clicked and cqlai selects text itself.",
			"Off, the terminal selects and pastes as it always does.",
		},
		Example: []string{"MOUSE OFF"},
	},
	{
		Name:    ".AI",
		Aliases: []string{"AI"},
		Summary: "Writes CQL from a request in plain words, for you to run.",
		Syntax:  []string{".AI request"},
		Notes: []string{
			"It needs an AI provider, set in FILE > PREFERENCES under CHAT. Nothing it",
			"writes runs until you press Enter on it.",
		},
		Example: []string{".AI the ten biggest orders this week"},
	},
}
